version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  rag-app:
    build: .
    container_name: rag-pdf-local
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - CHROMA_PERSIST_DIR=/app/data/chroma
    depends_on:
      - ollama
    command: streamlit run src/app.py --server.address=0.0.0.0

volumes:
  ollama_data:
